hakdog = "\n"
d1 = "\n\t\t\t\t\t\t\t\t\t\t*\t*"
d2 = "\n\t\t\t\t\t\t\t\t\t*\t\t\t*"
d3 = "\n\t\t\t\t\t\t\t\t*\t\t\t\t\t*"
d4 = "\n\t\t\t\t\t\t\t*\t\t\t\t\t\t\t*"
d5 = "\n\t\t\t\t\t\t*\t\t\t\t\t\t\t\t\t*"
d6 = "\n\t\t\t\t\t*\t\t\t\t\t\t\t\t\t\t\t*"
d7 = "\n\t\t\t\t*\t\t\t\t\t\t\t\t\t\t\t\t\t*"
d8 = "\n\t\t\t*\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t*"
d9 = "\n\t\t*\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t*"
d0 = "\n\t*\t\t\t\t\t\t\t\t      Hi! My name is\t\t\t\t\t\t\t\t\t*"
di1 = "\n\t*\t\t\t\t\t\t\t\t      \"Jemaika Mae\"\t\t\t\t\t\t\t\t\t*"
di2 = "\n\t\t*\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t*"
di3 = "\n\t\t\t*\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t*"
di4 = "\n\t\t\t\t*\t\t\t\t\t\t\t\t\t\t\t\t\t*"
di5 = "\n\t\t\t\t\t*\t\t\t\t\t\t\t\t\t\t\t*"
di6 = "\n\t\t\t\t\t\t*\t\t\t\t\t\t\t\t\t*"
di7 = "\n\t\t\t\t\t\t\t*\t\t\t\t\t\t\t*"
di8 = "\n\t\t\t\t\t\t\t\t*\t\t\t\t\t*"
di9 = "\n\t\t\t\t\t\t\t\t\t*\t\t\t*"
di0 = "\n\t\t\t\t\t\t\t\t\t\t*\t*"

print(hakdog, d1, d2, d3, d4, d5, d6, d7, d8, d9, d0, di1, di2, di3, di4, di5, di6, di7, di8, di9, di0)